1 2 add applications
thinknetica-django-lab-01/Buyankin pull request #10
Opened 2021-01-20 10:16 UTC by Buyankin

Closes #7

2021-01-20 14:06 UTC, mikhailborodin requested changes

2021-01-20 14:06 UTC, mikhailborodin commented on main/shop/urls.py
> +    path('about/', about, name='about'),
предполагалось что эти страницы управляются через приложение FlatPage, а вы сделали их напрямую. Страницы управляемые FlatPage доступны через /pages/, таким образом у вас должно открываться три страницы по адресам `/pages/about/ /pages/contact/ и /pages/`

2021-01-20 14:44 UTC, Buyankin commented
я установил FlatPage и через админку забил эти страницы.

Поправил адрес страниц

2021-01-21 04:51 UTC, mikhailborodin requested changes

2021-01-21 04:51 UTC, mikhailborodin commented on main/shop/urls.py
> +    path('pages/about/', about, name='about'),
используя flatpages так можно не делать, приложение само отвечает за диспетчеризация урлов, поставьте `path('pages/', include('django.contrib.flatpages.urls')),` и страницы about и contact вместо с урлами можно будет создать в админке. Поэтому вам не нужно создавать ни views ни templates для этих страниц, всё делает flatpages https://docs.djangoproject.com/en/3.1/ref/contrib/flatpages/

2021-01-21 07:18 UTC, Buyankin commented on main/shop/urls.py
> +    path('pages/about/', about, name='about'),
ну думаю, что поправил как вы написали

2021-01-21 17:50 UTC, mikhailborodin approved these changes

2021-01-22 04:31 UTC, merged