2 3 edit models
thinknetica-django-lab-01/Buyankin pull request #15
Opened 2021-01-24 11:31 UTC by Buyankin

Close #2

2021-01-24 20:03 UTC, mikhailborodin requested changes

2021-01-24 20:03 UTC, mikhailborodin commented on main/shop/migrations/0002_shop_price.py
> +# Generated by Django 3.1.5 on 2021-01-24 11:29
добавьте использование migrations.RunPython чтобы функция генерировала случайные числа от 1 до 100 и записывала их в новое поле для всех существующих записей

2021-01-26 16:41 UTC, Buyankin commented
что то запутался немного - но вроде все правильно исправил проверьте функцию set_random_price в миграции

2021-01-26 18:36 UTC, mikhailborodin approved these changes

2021-01-27 02:38 UTC, merged