install main
thinknetica-django-lab-01/Buyankin pull request #9
Opened 2021-01-19 05:33 UTC by Buyankin

Closes #8 install new project "main" in django

2021-01-19 11:06 UTC, mikhailborodin requested changes

2021-01-19 11:06 UTC, mikhailborodin commented on venv/bin/Activate.ps1
> +<#
папку venv и всё её содержимое надо удалить из репозитория  с сохранением локальных файлов и добавить в gitignore

2021-01-19 11:50 UTC, Buyankin commented on venv/bin/Activate.ps1
> +<#
создал gitignore (добавил исключения для venv и для Django)
venv удалил

2021-01-19 12:38 UTC, mikhailborodin requested changes

2021-01-19 12:38 UTC, mikhailborodin commented on main/main/settings.py
> +    'django.contrib.staticfiles',
вы назвали main'ом проект, хотя в задании было указано создать приложение main. Обычно проект называют "project", "store" etc а вот приложение может называться main

2021-01-19 12:45 UTC, Buyankin commented on main/main/settings.py
> +    'django.contrib.staticfiles',
ok

2021-01-19 13:57 UTC, Buyankin commented on main/main/settings.py
> +    'django.contrib.staticfiles',
назвал проект shop так пойдет? это имя подойдет?

2021-01-20 03:23 UTC, mikhailborodin approved these changes

2021-01-20 03:23 UTC, mikhailborodin commented on main/main/settings.py
> +    'django.contrib.staticfiles',
да. Только вы не проект назвали shop, а приложение

2021-01-20 06:39 UTC, merged